
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores.DracoScript;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int tk_cadena = 42;
  public static final int tk_menorigual = 30;
  public static final int tk_potencia = 22;
  public static final int pr_var = 2;
  public static final int tk_decimal = 45;
  public static final int tk_mas = 18;
  public static final int pr_string = 14;
  public static final int tk_por = 21;
  public static final int tk_mayorigual = 31;
  public static final int pr_oval = 13;
  public static final int tk_llader = 41;
  public static final int pr_true = 16;
  public static final int tk_division = 20;
  public static final int tk_ptcoma = 36;
  public static final int tk_adicion = 24;
  public static final int pr_line = 15;
  public static final int tk_parder = 39;
  public static final int pr_for = 8;
  public static final int tk_not = 34;
  public static final int tk_and = 32;
  public static final int pr_not = 4;
  public static final int tk_igualop = 26;
  public static final int UMENOS = 48;
  public static final int EOF = 0;
  public static final int pr_smash = 6;
  public static final int error = 1;
  public static final int pr_quadrate = 12;
  public static final int tk_igual = 35;
  public static final int tk_entero = 44;
  public static final int tk_caracter = 43;
  public static final int pr_runmultdasm = 10;
  public static final int tk_coma = 37;
  public static final int pr_point = 11;
  public static final int pr_elif = 5;
  public static final int tk_sustraccion = 25;
  public static final int pr_while = 7;
  public static final int tk_or = 33;
  public static final int tk_diferente = 27;
  public static final int pr_if = 3;
  public static final int tk_menos = 19;
  public static final int tk_menor = 28;
  public static final int tk_id = 46;
  public static final int tk_llaizq = 40;
  public static final int pr_false = 17;
  public static final int tk_mayor = 29;
  public static final int tk_parizq = 38;
  public static final int pr_print = 9;
  public static final int tk_archivo = 47;
  public static final int tk_modulo = 23;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "pr_var",
  "pr_if",
  "pr_not",
  "pr_elif",
  "pr_smash",
  "pr_while",
  "pr_for",
  "pr_print",
  "pr_runmultdasm",
  "pr_point",
  "pr_quadrate",
  "pr_oval",
  "pr_string",
  "pr_line",
  "pr_true",
  "pr_false",
  "tk_mas",
  "tk_menos",
  "tk_division",
  "tk_por",
  "tk_potencia",
  "tk_modulo",
  "tk_adicion",
  "tk_sustraccion",
  "tk_igualop",
  "tk_diferente",
  "tk_menor",
  "tk_mayor",
  "tk_menorigual",
  "tk_mayorigual",
  "tk_and",
  "tk_or",
  "tk_not",
  "tk_igual",
  "tk_ptcoma",
  "tk_coma",
  "tk_parizq",
  "tk_parder",
  "tk_llaizq",
  "tk_llader",
  "tk_cadena",
  "tk_caracter",
  "tk_entero",
  "tk_decimal",
  "tk_id",
  "tk_archivo",
  "UMENOS"
  };
}

